name: Trigger auto deployment for container-app-hjurh27hplros

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-hjurh27hplros-AutoDeployTrigger-a8e3a084-21dc-49a6-96ba-b49ff3714f98.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPHJURH27HPLROS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPHJURH27HPLROS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPHJURH27HPLROS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPHJURH27HPLROS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPHJURH27HPLROS_REGISTRY_PASSWORD }}
          containerAppName: container-app-hjurh27hplros
          resourceGroup: flaskbasicb79f9c9f
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


